sudo: required
services:
  - docker
before_install:
  - docker build -t suy/docker-react -f Dockerfile .
script: 
  - docker run  -e CI=true suy/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env-1"
  bucker_name: "elasticbeanstalk-ap-south-1-781874652364"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
